### PR TITLE
edge provenance attribute mapping

### PR DESCRIPTION
**Pull request by YaphetKG**
Adds attribute mapping for cypher transpiler to use when intercepting neo4j attributes that have that attribute name to be mapped with biolink specified items.

### CODE REVIEW

**Review by PhillipsOwen — APPROVED** [review]
dam you are good!

**Comment by patrickkwang** [comment]
Huh. I didn't anticipate anyone doing that, but it works! A more sensible API might be to allow configuring that in the `get_query` call.

**Comment by YaphetKG** [comment]
@patrickkwang  agree, is that already a feature in the transpiler maybe I missed it?

**Comment by patrickkwang** [comment]
It is not, but I'll make an issue for it.

**Pull request merged**
